version: '3.8'
services:
  nextjs:
    image: the-internet-wishlist-dev
    container_name: nextjs
    build: .
    env_file:
      - .env.development.local
    ports:
      - '${PORT}:3000'
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis:/data
volumes:
  redis:
  mongo: